stringindex_ = 0;
var arrayIndex =0;
global.textindex_ = 0;
global.stringComp = "123456";
var _year = string(1970 - global.year_);
create_text( arrayIndex,texttype.simple, "It is " + _year + ". Your jumping off");
create_text( arrayIndex,texttype.simple, "place for Oregon is Independence,");
create_text( arrayIndex,texttype.simple, "Missouri. You must decide which");
create_text( arrayIndex,texttype.simple, "month to leave Independence.");
create_text( arrayIndex,texttype.simple, "");
create_text(arrayIndex,texttype.simple, "  1. March ");
create_text(arrayIndex,texttype.simple, "  2. April");
create_text(arrayIndex,texttype.simple, "  3. May");
create_text(arrayIndex,texttype.simple, "  4. June");
create_text(arrayIndex,texttype.simple, "  5. July");
create_text(arrayIndex,texttype.simple, "  6. Ask for advice");
create_text(arrayIndex,texttype.simple, "");
create_text(arrayIndex,texttype.simple, "");
create_text(arrayIndex,texttype.number, "What is your choice? ");
create_text(arrayIndex,texttype.simple, "");
create_text(arrayIndex,texttype.simple, "");
create_text(arrayIndex,texttype.simple, "");
create_text(arrayIndex,texttype.simple, "");
create_text(arrayIndex,texttype.simple, "");

arrayIndex++;
stringindex_ = 0;

create_text(arrayIndex,texttype.simple, "You attend a public meeting held");
create_text(arrayIndex,texttype.simple, "for \"folks with the Oregon");
create_text(arrayIndex,texttype.simple, "fever.\" You're told: ");
create_text(arrayIndex,texttype.simple, "");
create_text(arrayIndex,texttype.simple, "If you leave too early, there");
create_text(arrayIndex,texttype.simple, "won't be any grass for your");
create_text(arrayIndex,texttype.simple, "oxen to eat. If you leave too");
create_text(arrayIndex,texttype.simple, "late, you may not get to Oregon");
create_text(arrayIndex,texttype.simple, "before winter comes. If you");
create_text(arrayIndex,texttype.simple, "leave at just the right time");
create_text(arrayIndex,texttype.simple, "there will be green grass and");
create_text(arrayIndex,texttype.simple, "the weather will still be cool.");
create_text(arrayIndex,texttype.simple, "");
create_text(arrayIndex,texttype.simple, "");
create_text(arrayIndex,texttype.simple, "");
create_text(arrayIndex,texttype.simple, "");
create_text(arrayIndex,texttype.simple, "");
create_text(arrayIndex,texttype.simple, "");
create_text(arrayIndex,texttype.simple, "");
create_text(arrayIndex,texttype.center, "Press SPACE BAR to continue");

stringindex_ = 0;